#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" --dbname "${POSTGRES_USER}" <<-EOSQL
    CREATE USER "${POSTGRES__DBUSER}" WITH PASSWORD '${POSTGRES__DBPASS}';
    CREATE DATABASE "${POSTGRES__DBNAME}";
    GRANT ALL PRIVILEGES ON DATABASE "${POSTGRES__DBNAME}" to "${POSTGRES__DBUSER}";
    ALTER DATABASE "${POSTGRES__DBNAME}" OWNER TO "${POSTGRES__DBUSER}";
EOSQL
